{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ketchup-web-app-template-1.serviceAccountName" . }}
  labels:
{{ include "ketchup-web-app-template-1.labels" . | nindent 4 }}
{{- end -}}
