FROM ${aspdotnetcore.sdk.image.name} AS build-env
WORKDIR /app

#changing project location causes issues in serving static content leading to 404 errors.
# Copy csproj from /workspace/output to /app/project-location and restore as distinct layers
COPY *.sln /app/
COPY ./${dotnetcore.project.location}/*.csproj /app/${dotnetcore.project.location}/
RUN dotnet restore

# Copy everything else and build
COPY ./${dotnetcore.project.location}/. /app/${dotnetcore.project.location}/
WORKDIR /app/${dotnetcore.project.location}
RUN dotnet publish -c release -o out --no-restore

# Build runtime image
FROM ${aspdotnetcore.runtime.image.name}
WORKDIR /app
COPY --from=build-env /app/${dotnetcore.project.location}/out /app
EXPOSE ${app.port}
ENTRYPOINT ["/bin/sh", "-c", "dotnet /app/*[^.Views].dll"]