FROM ${maven.image.name} as builder
WORKDIR /app
COPY pom.xml /app/pom.xml
RUN mvn -B dependency:resolve dependency:resolve-plugins -T1.5C -Dmaven.repo.local=/tmp/m2
COPY src /app/src
RUN mvn -B -o -Dmaven.test.skip -Dmaven.repo.local=/tmp/m2 -T1.5C package

FROM ${jre.image.name}
WORKDIR /app
COPY --from=builder /app/target /app/target
EXPOSE ${app.port}
CMD ["/bin/sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app/target/*.jar"]
