FROM python:3.8-alpine

WORKDIR /app
ADD ./* /app/
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE ${app.port}
CMD ["gunicorn", "--bind", "0.0.0.0:${app.port}", "${gunicorn.app.location}"]

