FROM ${aspdotnetcore.sdk.image.name} AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp/*.csproj ./aspnetapp/
RUN dotnet restore

# Copy everything else and build
COPY aspnetapp/. ./aspnetapp/
WORKDIR /app/aspnetapp
RUN dotnet publish -c release -o out --no-restore

# Build runtime image
FROM ${aspdotnetcore.runtime.image.name}
WORKDIR /app
COPY --from=build-env /app/aspnetapp/out /app
EXPOSE ${app.port}
ENTRYPOINT ["/bin/sh", "-c", "dotnet /app/*[^.Views].dll"]