FROM ${maven.image.name} as builder
WORKDIR /app
COPY pom.xml /app/pom.xml
RUN mvn -B dependency:resolve dependency:resolve-plugins -T1.5C -Dmaven.repo.local=/tmp/m2
COPY src /app/src
RUN mvn -B -o -Dmaven.test.skip -Dmaven.repo.local=/tmp/m2 -T1.5C package

FROM ${jre.image.name}
WORKDIR /app
COPY --from=builder /app/target/${app.jar.name} /app/app.jar
EXPOSE ${app.port}
ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar app.jar
