FROM ${node.image.name}
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json /app/

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./ /app/
RUN npm run build

WORKDIR /app/build
RUN npm install -g serve@11.3.2
EXPOSE ${app.port}
CMD [ "serve", "-s", "-l", "${app.port}" ]
