FROM ${golang.image.name} as base
WORKDIR /app
ENV CGO_ENABLED=0
COPY go.* /app/
RUN go mod download
COPY ./* /app/
RUN go build -o main .

FROM ${golang.image.name}
WORKDIR /app
COPY --from=base /app/main /app/
EXPOSE ${app.port}
CMD ["/app/main"]
