apiVersion: v1
kind: Secret
metadata:
  name: ${gitRepoSecretName}
  annotations:
    tekton.dev/git-0: ${gitRepoBaseUrl}
type: kubernetes.io/basic-auth
stringData:
  username: ${gitRepoUsername}
  password: ${gitRepoPassword}