apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ${pipelineName}
spec:
  resources:
    - name: ${gitResourceName}
      type: git
  tasks:
    - name: build-image
      taskRef:
        name: ${makisuBuildImageTaskName}
      resources:
        inputs:
          - name: ${gitResourceName}
            resource: ${gitResourceName}
      params:
        - name: MAKISU_IMAGE
          value: gcr.io/uber-container-tools/makisu:v0.1.14
        - name: WORKSPACE
          value: /workspace/${gitResourceName}
        - name: IMAGE_REGISTRY_URL
          value: ${containerRegistryUrl}
        - name: MAKISU_ARG_MODIFY_FS
          value: "true"
        - name: IMAGE_TAG
          value: ${imageTag}
        - name: MAKISU_CONTEXT_PATH
          value: .
        - name: MAKISU_CACHE_REDIS_ADDR
          value: redis-1585680551-master.default.svc.cluster.local:6379
        - name: MAKISU_CACHE_REDIS_PASSWORD
          value: Oi25VLvMZF
    - name: deploy-chart-in-cluster
      taskRef:
        name: ${helmDeployTaskName}
      params:
        - name: HELM_IMAGE
          value: alpine/helm:latest
        - name: WORKSPACE
          value: /workspace/${gitResourceName}
        - name: KUBECONFIG_FILE_NAME
          value: kubeconfig
        - name: HELM_CHART_URL
          value: ${helmChartUrl}
        - name: HELM_CHART_RELEASE_NAME
          value: ${helmReleaseName}
        - name: KUBERNETES_NAMESPACE
          value: ${devKubernetesNamespace}
        - name: HELM_COMMAND
          value: ${helmCommand}
      runAfter:
        - build-image