apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-springboot-demo-ketchup.fullname" . }}
  labels:
    {{- include "basic-springboot-demo-ketchup.labels" . | nindent 4 }}
    applicationRevisionId: {{ .Values.applicationRevisionId }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy}}
  selector:
    matchLabels:
      {{- include "basic-springboot-demo-ketchup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basic-springboot-demo-ketchup.selectorLabels" . | nindent 8 }}
        applicationRevisionId: {{ .Values.applicationRevisionId }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "basic-springboot-demo-ketchup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
