apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ketchup-core.fullname" . }}
  labels:
    {{- include "ketchup-core.labels" . | nindent 4 }}
data:
  application.properties: |-
     {{ required "Please provide a valid application configuration file by setting property applicationProperties." .Values.applicationProperties | b64enc }}