{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ketchup-core.serviceAccountName" . }}
  labels:
{{ include "ketchup-core.labels" . | nindent 4 }}
{{- end -}}
