apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: ${pipelineRunName}
spec:
  serviceAccountName: ${serviceAccountName}
  pipelineRef:
    name: ${pipelineName}
  resources:
    - name: ${gitResourceName}
      resourceRef:
        name: ${gitResourceName}
