apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ${pipelineRunName}
spec:
  timeout: "3h"
  serviceAccountName: ${serviceAccountName}
  pipelineRef:
    name: ${pipelineName}
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: ${pipelinePvcName}
  params:
    - name: "git-url"
      value: "${gitRepoUrl}"
    - name: "git-revision"
      value: "${gitRevision}"
    - name: "makisu-image-name"
      value: "gcr.io/uber-container-tools/makisu:v0.1.14"
    - name: "image-registry-url"
      value: "${containerRegistryUrl}"
    - name: "image-tag"
      value: "${imageTag}"
    - name: "makisu-cache-redis-addr"
      value: "${redisUrl}"
    - name: "makisu-cache-redis-password"
      value: "${redisPassword}"
    - name: "makisu-build-context-path"
      value: "${buildContextPath}"
    - name: "helm-image-name"
      value: "alpine/helm:latest"
    - name: "helm-chart-url"
      value: "${helmChartUrl}"
    - name: "helm-chart-release-name"
      value: "${helmReleaseName}"
    - name: "kubernetes-namespace"
      value: "${devKubernetesNamespace}"
    - name: "helm-command"
      value: "${helmCommand}"
