apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${pipelineName}
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: makisu-image-name
    - name: image-registry-url
    - name: image-tag
    - name: makisu-cache-redis-addr
    - name: makisu-cache-redis-password
    - name: helm-image-name
    - name: helm-chart-url
    - name: helm-chart-release-name
    - name: kubernetes-namespace
    - name: helm-command
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-source-code
      Timeout: "30m"
      taskRef:
        name: ${gitCloneTaskName}
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    - name: build-image
      Timeout: "1h"
      taskRef:
        name: ${makisuBuildImageTaskName}
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: MAKISU_IMAGE
          value: $(params.makisu-image-name)
        - name: IMAGE_REGISTRY_URL
          value: $(params.image-registry-url)
        - name: MAKISU_ARG_MODIFY_FS
          value: "true"
        - name: IMAGE_TAG
          value: $(params.image-tag)
        - name: MAKISU_CONTEXT_PATH
          value: .
        - name: MAKISU_CACHE_REDIS_ADDR
          value: $(params.makisu-cache-redis-addr)
        - name: MAKISU_CACHE_REDIS_PASSWORD
          value: $(params.makisu-cache-redis-password)
      runAfter:
        - fetch-source-code
    - name: deploy-chart-in-cluster
      Timeout: "1h"
      taskRef:
        name: ${helmDeployTaskName}
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: HELM_IMAGE
          value: $(params.helm-image-name)
        - name: KUBECONFIG_FILE_NAME
          value: kubeconfig
        - name: HELM_CHART_URL
          value: $(params.helm-chart-url)
        - name: HELM_CHART_RELEASE_NAME
          value: $(params.helm-chart-release-name)
        - name: KUBERNETES_NAMESPACE
          value: $(params.kubernetes-namespace)
        - name: HELM_COMMAND
          value: $(params.helm-command)
      runAfter:
        - build-image